services:
  app:
    build: .
    image: redbox-ddns
    ports:
      - '3001:3001'
    volumes:
      - '/data/storage/redbox-ddns/users.json:/usr/src/app/users.json'
    environment:
      USERS_FILE: /usr/src/app/users.json
    restart: unless-stopped
